{% set name = "ldap" %}
{% set version = "2.0.0.404" %}
{% set hash_type = "sha256" %}
{% set hash_value = "60da99f3c93a9667737e5fea7e692bb0a6fa649ceb488c51aed603e0e7c39433" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  entry_points:
    - ldap = ldap:main
  script: python -m pip install . --no-deps --ignore-installed
  noarch: python

requirements:
  build:
    - pip
    - python
    - setuptools
  run:
    - python
    - ldap3

test:
  imports:
    - ldap
  commands:
    - ldap --help

about:
  home: https://github.com/andreif/ldap
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: LDAP utils.
  description: 'LDAP utils'

extra:
  recipe-maintainers:
    - nicoddemus
