travis:
  secure:
    BINSTAR_TOKEN: a4pyfe7Ycr6VpSZ4UmIdNI0ikYcI6lwJ3vp2EoW1J2NMpHM6JmBt8QaU8BND76xu5/z805iuqpg7myGfiD8ZZ+pVPdCxD8VeV7six7tvgdSjQNMy0wlfZHE3SWZYRM+QlCfCdR0KrBCPMQTfC1K20DZvrTLtbg52HhNIoIMIFWpt8JaSaa5G7KuV4EOxYEl9KvQVUZfF9rxAmaAOEYfmJb7KaYSPia2KNs477ikuS6Hddlie8/35iIBYwjjinonNpfAu6PF2DJ7xdrGazwJ2Jp8RwjDiQtz3i6pwFe5f/YADFFylBv+KOyN+oOxqlmenA2G6T0w/kLG6WfaXUnv/mB/PRpa1W32xCcoT6xLag7KRRvJP9inhljxIhb5wlACxdLqFKE7q1+4JemAhtUoB88aQvS6npBlkTANHWtws/tVItgWljyH/+oKprx0QDjhKWyfvoYMMelDLfiq1zU2tA1YpN5eZdbi1S+4hv3uSsN6HrcqBJ+bWkDRW/NqqacDhOfk+6hGMeFWAw0mNLEllINHdYKHiwR94j4jFpfTz35Rhmt1cmvSNPd0Et/SP6kgEXZinjyifRSDL45a2dqDHW8sgxmyJrxwBelUG6N8ExO/+pbo4LA/df/fSXZXMbK4DocQe5CZT2ctitJ9GS7xL74pe5XiCrsmClq8Vn/EIXsQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
