travis:
  secure:
    BINSTAR_TOKEN: eaR6BKcPV6L92OpLDp/hJVXzflNnaWhivQRoMlLDiWC/kSeGfK/y2+CYYKmFTLyq5lOITNbuziQtS7CUsY16/LXjUjD2qBgvrJpzHvAizjLszQbW+ZhvY9rqyo0Lnk7ejsjY9ZhzYsN5CPStxNp3uGXMqv7l0Zjv2roWM85iFu2f4E5DyBrPHecqyDrMTSNhCtkJXKFdZObDgK31BCbRjEneW5XRi/QJaxh0NIvWPFjpbG8CaNK3hJzrujiHasMIkB01oPmNySjnfspJImPanIE77DyebZn4vp+HmX5vrrvINdNPfj0XjKs42r8ivmxHksEbnSbaFN1pRKRBr+PSD9xbrlWRHolTl7FFIFutpitknkUyoXupgKspmLBy5W9BoDQU1yQxW0WkXKQJVB1YW++JXieQGR1N5TuullQrEgkAcbwjBsbb0j4b0X97EjcZo/WBOBDM6NCR0/HeHelY3Avf/IjWCp8dwoi1g/TMHICJerK1pQfZwFu4KlTYVYurrIsid/oek2LAvuKFu82IJ59O2KHFbL1U6bBDfTx0CJXs67mHlTpCkuvXqq3/G8JsXvfeekiqyQddYWElWjl2uvjDoCQT6Q5pZDZhBV4xkHOnOyZD5yWzFQdU8V6POGRVPv0tEv3Y39Kt6aw1BSEQjuzycMFZPlwbc85khdqLnW8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
